### ISSUE TITLE
List continuation does not work with YAML code block

### ISSUE THREAD

**Issue by apinnick** [asciidoctor/kramdown-asciidoc#110]
List continuation ("+") works with indented bash code block but not with indented yaml code block.

https://github.com/asciidoctor/kramdown-asciidoc/pull/111

**Comment by mojavelinux** [comment]
You have not used enough indentation. The list content has to be indented at least as much as the principal list text. You have intended 2 characters. It needs to be at least 3, and in some Markdown implementations, it must be 4.

Please verify you have the correct Markdown syntax before raising issues here. This is not a support portal for Markdown. You can check if you have the right syntax by running kramdown on your Markdown file or by using a Markdown editor.
