### ISSUE TITLE
Support for Markdown-style blockquote

### ISSUE THREAD

**Issue by Taack** [asciidoctor/kramdown-asciidoc#121]
Could it be possible to let pass through markdown blockquotes ?

It is easier to parse IMO. I do not find a way to do so. 

See https://docs.asciidoctor.org/asciidoc/latest/blocks/blockquotes/#ex-md-block
for markdown style blockquotes.

Regards

**Comment by mojavelinux** [comment]
No, Markdown-style syntax in AsciiDoc is not official and therefore should not be encouraged. The focus of this converter is on converting from Markdown to standard AsciiDoc.

**Comment by Taack** [comment]
Understood. I am creating an Asciidoctor online editor, integrated to our framework (https://taack.org), I will try to comply the standard the most.

We used Markdown previously with server side rendering, this time the rendering is done directly into the browser (except for diagrams). We are also adding some Asciidoc extensions to query and present objects manipulated by our Framework (see  https://taack.org/en/app/Intercom#_tql_and_tdl_inlined_into_asciidoc )

Anyway, thanks for your work, have a nice day.

**Comment by mojavelinux** [comment]
> I am creating an Asciidoctor online editor, integrated to our framework (taack.org)

Awesome to hear it!

We welcome you to join us in the project chat at https://chat.asciidoctor.org to discuss all things Asciidoctor and AsciiDoc.
