### ISSUE TITLE
Unable to converto to Asciidoc, `method_missing': undefined method `to_e.adoc'·

### ISSUE THREAD

**Issue by gabrielmontagne** [asciidoctor/kramdown-asciidoc#73]
Hi, 

I'm running `ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]`, 
and installed kramdown from the public gems repo which is, at this moment, `kramdown-asciidoc-1.0.1`

I tried to use it convert a markdown file to asciidoc and got the following exception,

```
(base) gabriel@yvon:~$ kramdown -o e.adoc export-tree.md 
/var/lib/gems/2.3.0/gems/kramdown-1.17.0/lib/kramdown/document.rb:121:in `method_missing': undefined method `to_e.adoc' for #<Kramdown::Document:0x005588f7a8ee88> (NoMethodError)
        from /var/lib/gems/2.3.0/gems/kramdown-1.17.0/bin/kramdown:98:in `block in <top (required)>'
        from /var/lib/gems/2.3.0/gems/kramdown-1.17.0/bin/kramdown:98:in `each'
        from /var/lib/gems/2.3.0/gems/kramdown-1.17.0/bin/kramdown:98:in `<top (required)>'
        from /usr/local/bin/kramdown:22:in `load'
        from /usr/local/bin/kramdown:22:in `<main>'
```

**Comment by mojavelinux** [comment]
You have mistyped the command. The command is `kramdoc`, not `kramdown`. `kramdoc` (the command for this gem) takes you from Markdown to AsciiDoc. `kramdown` (which is a command from a different gem) converts from Markdown to HTML.

**Comment by gabrielmontagne** [comment]
I totally did mistype the command.  Sorry for the noise!
