### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by mavogel** [asciidoctor/kramdown-asciidoc#75]
Add your bundle/binary to a Dockerfile and release it to Dockerhub. I'd love to integrate and use it in my CI pipelines. 

Is it planned? If not I'd contribute

**Comment by mojavelinux** [comment]
Docker containers are handled by https://github.com/asciidoctor/docker-asciidoctor.

**Comment by mavogel** [comment]
Thanks for the hint! As it is not in in the `$PATH`
```sh
docker run -it asciidoctor/docker-asciidoctor
bash-5.0# which kramdoc
which: no kramdoc in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
```

I assume I'd rather contribute it to the repository you mentioned right?

**Comment by mojavelinux** [comment]
That's correct.

**Comment by ehmkah** [comment]
@mavogel - think this issue could be close because there is a PR https://github.com/asciidoctor/docker-asciidoctor/pull/120 which has been merge and which includes kramdown.

**Comment by mavogel** [comment]
Awesome @ehmkah :) thanks for the heads-up. I'll close this one here.
