### ISSUE TITLE
converting markdown containing yaml headers

### ISSUE THREAD

**Issue by aisbergde** [asciidoctor/kramdown-asciidoc#95]
Some of my markdown files contain yaml headers, but this causes errors when I try to convert. The files are starting like:

```
---
title:  'Convert OneNote to MarkDown'
author:
- Sjoerd de Valk, SPdeValk Consultancy
date: 2019-05-19 22:35:00
keywords: [migration, tooling, onenote, markdown]
abstract: |
  This document is about converting your OneNote data to Markdown format.
---
```

or

```
---
title: graph data in mssql
tags:
  - graph
  - mssql
  - visjs
date: 2021-01-05T14:00:26.470Z
draft: true
slug: graph-data-mssql
---
```

**Comment by aisbergde** [comment]
but most yaml headers can be converted, for example this one converts fine:

```
---
tags: [android, editor]
title: android editor
created: '2020-05-28T05:58:00.163Z'
modified: '2020-05-30T12:54:27.060Z'
---
```

**Comment by erikvanberkum** [comment]
Upgraded to version 2 today came from version 1. Version 2 seems to trip over the date field. 

---
title: title of the page
description:  just a description
published: true
date: 2021-06-15T13:46:42.889Z
tags: tags, tags, tags
editor: markdown
dateCreated: 2020-12-16T09:09:23.481Z
---

When my date and datecreated fields are in quotes '2020-12-16T09:09:23.481Z' it runs perfectly fine.

Below is are my errors:

Traceback (most recent call last):
        31: from C:/Ruby27-x64/bin/kramdoc:23:in `<main>'
        30: from C:/Ruby27-x64/bin/kramdoc:23:in `load'
        29: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/kramdown-asciidoc-2.0.0/bin/kramdoc:13:in `<top (required)>'
        28: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/kramdown-asciidoc-2.0.0/lib/kramdown-asciidoc/cli.rb:120:in `run'
        27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/kramdown-asciidoc-2.0.0/lib/kramdown-asciidoc/api.rb:107:in `convert_file'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/kramdown-asciidoc-2.0.0/lib/kramdown-asciidoc/api.rb:52:in `convert'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/kramdown-asciidoc-2.0.0/lib/kramdown-asciidoc/api.rb:52:in `each'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/kramdown-asciidoc-2.0.0/lib/kramdown-asciidoc/api.rb:53:in `block in convert'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/kramdown-asciidoc-2.0.0/lib/kramdown-asciidoc/api.rb:53:in `[]'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/kramdown-asciidoc-2.0.0/lib/kramdown-asciidoc/preprocessors.rb:21:in `extract_front_matter'
        21: from C:/Ruby27-x64/lib/ruby/2.7.0/psych.rb:360:in `safe_load'
        20: from C:/Ruby27-x64/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:32:in `accept'
        19: from C:/Ruby27-x64/lib/ruby/2.7.0/psych/visitors/visitor.rb:6:in `accept'
        18: from C:/Ruby27-x64/lib/ruby/2.7.0/psych/visitors/visitor.rb:16:in `visit'
        17: from C:/Ruby27-x64/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:313:in `visit_Psych_Nodes_Document'
        16: from C:/Ruby27-x64/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:32:in `accept'
        15: from C:/Ruby27-x64/lib/ruby/2.7.0/psych/visitors/visitor.rb:6:in `accept'
        14: from C:/Ruby27-x64/lib/ruby/2.7.0/psych/visitors/visitor.rb:16:in `visit'
        13: from C:/Ruby27-x64/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:162:in `visit_Psych_Nodes_Mapping'
        12: from C:/Ruby27-x64/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:338:in `revive_hash'
        11: from C:/Ruby27-x64/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:338:in `each_slice'
        10: from C:/Ruby27-x64/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:338:in `each'
         9: from C:/Ruby27-x64/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:340:in `block in revive_hash'
         8: from C:/Ruby27-x64/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:32:in `accept'
         7: from C:/Ruby27-x64/lib/ruby/2.7.0/psych/visitors/visitor.rb:6:in `accept'
         6: from C:/Ruby27-x64/lib/ruby/2.7.0/psych/visitors/visitor.rb:16:in `visit'
         5: from C:/Ruby27-x64/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:123:in `visit_Psych_Nodes_Scalar'
         4: from C:/Ruby27-x64/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:60:in `deserialize'
         3: from C:/Ruby27-x64/lib/ruby/2.7.0/psych/scalar_scanner.rb:53:in `tokenize'
         2: from C:/Ruby27-x64/lib/ruby/2.7.0/psych/scalar_scanner.rb:110:in `parse_time'
         1: from C:/Ruby27-x64/lib/ruby/2.7.0/psych/class_loader.rb:28:in `load'
C:/Ruby27-x64/lib/ruby/2.7.0/psych/class_loader.rb:97:in `find': Tried to load unspecified class: Time (Psych::DisallowedClass)

Anyone any suggestions how to create quotes around the date field. My data is generated from a  [wiki.js](https://js.wiki/) site?
Or anyone knows how to downgrade back to version 1?

**Comment by erikvanberkum** [comment]
I went back to version [1.0.1](https://rubygems.org/gems/kramdown-asciidoc/versions/1.0.1) it's too much work to manually edit all the yaml headers before processing with kramdoc.

**Comment by settermjd** [comment]
I encountered what I believe is the same issue, today. On attempting to convert a Markdown file, I encountered the following error:

```bash
kramdoc --format=GFM \
    --output=getting-started.adoc \
    --wrap=ventilate \
    2020-07-28-mezzio-getting-started-is-live.md
/usr/lib/ruby/3.0.0/psych/class_loader.rb:99:in `find': Tried to load unspecified class: Date (Psych::DisallowedClass)
	from /usr/lib/ruby/3.0.0/psych/class_loader.rb:28:in `load'
	from (eval):2:in `date'
	from /usr/lib/ruby/3.0.0/psych/scalar_scanner.rb:60:in `tokenize'
	from /usr/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:64:in `deserialize'
	from /usr/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:127:in `visit_Psych_Nodes_Scalar'
	from /usr/lib/ruby/3.0.0/psych/visitors/visitor.rb:30:in `visit'
	from /usr/lib/ruby/3.0.0/psych/visitors/visitor.rb:6:in `accept'
	from /usr/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:34:in `accept'
	from /usr/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:343:in `block in revive_hash'
	from /usr/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:341:in `each'
	from /usr/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:341:in `each_slice'
	from /usr/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:341:in `revive_hash'
	from /usr/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:166:in `visit_Psych_Nodes_Mapping'
	from /usr/lib/ruby/3.0.0/psych/visitors/visitor.rb:30:in `visit'
	from /usr/lib/ruby/3.0.0/psych/visitors/visitor.rb:6:in `accept'
	from /usr/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:34:in `accept'
	from /usr/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:317:in `visit_Psych_Nodes_Document'
	from /usr/lib/ruby/3.0.0/psych/visitors/visitor.rb:30:in `visit'
	from /usr/lib/ruby/3.0.0/psych/visitors/visitor.rb:6:in `accept'
	from /usr/lib/ruby/3.0.0/psych/visitors/to_ruby.rb:34:in `accept'
	from /usr/lib/ruby/3.0.0/psych.rb:361:in `safe_load'
	from /var/lib/gems/3.0.0/gems/kramdown-asciidoc-2.0.0/lib/kramdown-asciidoc/preprocessors.rb:21:in `extract_front_matter'
	from /var/lib/gems/3.0.0/gems/kramdown-asciidoc-2.0.0/lib/kramdown-asciidoc/api.rb:53:in `[]'
	from /var/lib/gems/3.0.0/gems/kramdown-asciidoc-2.0.0/lib/kramdown-asciidoc/api.rb:53:in `block in convert'
	from /var/lib/gems/3.0.0/gems/kramdown-asciidoc-2.0.0/lib/kramdown-asciidoc/api.rb:52:in `each'
	from /var/lib/gems/3.0.0/gems/kramdown-asciidoc-2.0.0/lib/kramdown-asciidoc/api.rb:52:in `convert'
	from /var/lib/gems/3.0.0/gems/kramdown-asciidoc-2.0.0/lib/kramdown-asciidoc/api.rb:107:in `convert_file'
	from /var/lib/gems/3.0.0/gems/kramdown-asciidoc-2.0.0/lib/kramdown-asciidoc/cli.rb:120:in `run'
	from /var/lib/gems/3.0.0/gems/kramdown-asciidoc-2.0.0/bin/kramdoc:13:in `<top (required)>'
	from /usr/local/bin/kramdoc:25:in `load'
	from /usr/local/bin/kramdoc:25:in `<main>'
```

This is the date in the YAML frontmatter: `date: 2020-07-28`. After wrapping the date in double quotes, the command works perfectly.

**Comment by mojavelinux** [comment]
Ruby 3 changed the YAML API. It reverted to safe by default. This impacts the parsing of YAML that uses types other than primitives. Until a fix is applied, you'd need to use Ruby < 3 to work around this issue.

**Comment by settermjd** [comment]
> Ruby 3 changed the YAML API. It reverted to safe by default. This impacts the parsing of YAML that uses types other than primitives. Until a fix is applied, you'd need to use Ruby < 3 to work around this issue.

Thanks for the rapid feedback, @mojavelinux. I'll further update my article.

**Comment by mojavelinux** [comment]
Upon further review, I have determined that this is not a Ruby 3.1 issue. Rather, this converter has never considered the case when the front matter value is parsed as a date as there was no test for it. I have added Date to the permitted classes and added a test. Once that fix is merged, it will work as expected.

I wish there was a way to tell the YAML parser to not attempt to parse a string that matches the syntax of a date, but that doesn't seem to be possible.

**Comment by settermjd** [comment]
> Upon further review, I have determined that this is not a Ruby 3.1 issue. Rather, this converter has never considered the case when the front matter value is parsed as a date as there was no test for it. I have added Date to the permitted classes and added a test. Once that fix is merged, it will work as expected.
> 
> I wish there was a way to tell the YAML parser to not attempt to parse a string that matches the syntax of a date, but that doesn't seem to be possible.

Thanks for the update, @mojavelinux!
